import React from 'react'
import { BsTwitter, BsFacebook } from 'react-icons/bs'
import { FaGithub } from 'react-icons/fa'
import { MdEmail } from 'react-icons/md'
import { MovingComponent } from 'react-moving-text'

import './header.css'
import ai from '../../assets/dalle1.png'

const Header = () => {
  return (
    <div className='site__header section__padding'>
      <div className='site__header-content'>
        <h1 className='gradient__text'>
          <MovingComponent type="typewriter"
            dataText={[
              'Welcome to',
              'AI @ Princeton!'
            ]} />
        </h1>
        <p className="">AI @ Princeton is an undergraduate organization at Princeton University dedicated to AI! </p>
        <p></p>
        <p> Our aim is to create a place to expose Princeton undergrads to the state of the art of AI research in an accessible way. We hope that this website will serve as a central hub for announcements and resources that our club members are working hard to put out for anyone interested in doing AI at Princeton! </p>
        <p></p>
        <div className='header__socials'>
          <a href="https://twitter.com" rel="noopener noreferrer"><BsTwitter size={40} /></a>
          <a href="https://github.com" rel="noopener noreferrer"><FaGithub size={40} /></a>
          <a href="https://facebook.com" rel="noopener noreferrer"><BsFacebook size={40} /></a>
          <a href="https://listserv.com" rel="noopener noreferrer">< MdEmail size={40} /></a>
        </div>
      </div>
      <div className='site__header-image'>
        <img src={ai} alt="Generated by DALL-E2"></img>
      </div>
    </div>
  )
}

export default Header